### ISSUE TITLE
Error Running Orbit Example

### ISSUE THREAD

**Issue by 1412kauti** [Toni-SM/skrl#67]
```
(orbit2) kaito@comet:~/Documents/Expt/Orbit/Project_Code$ orbit -p ppo_lift_franka.py 
[INFO] Using python from: /home/kaito/mambaforge-pypy3/envs/orbit2/bin/python                                                                                                                                     
Traceback (most recent call last):
  File "ppo_lift_franka.py", line 5, in <module>
    from skrl.models.torch import Model, GaussianMixin, DeterministicMixin
  File "/home/kaito/mambaforge-pypy3/envs/orbit2/lib/python3.7/site-packages/skrl/models/torch/__init__.py", line 1, in <module>
    from skrl.models.torch.base import Model
  File "/home/kaito/mambaforge-pypy3/envs/orbit2/lib/python3.7/site-packages/skrl/models/torch/base.py", line 4, in <module>
    import gymnasium
  File "/home/kaito/mambaforge-pypy3/envs/orbit2/lib/python3.7/site-packages/gymnasium/__init__.py", line 12, in <module>
    from gymnasium.envs.registration import (
  File "/home/kaito/mambaforge-pypy3/envs/orbit2/lib/python3.7/site-packages/gymnasium/envs/__init__.py", line 382, in <module>
    load_plugin_envs()
  File "/home/kaito/mambaforge-pypy3/envs/orbit2/lib/python3.7/site-packages/gymnasium/envs/registration.py", line 565, in load_plugin_envs
    for plugin in metadata.entry_points(group=entry_point):
TypeError: entry_points() got an unexpected keyword argument 'group'
```
I've tried to run the example for Orbit using SKRL, I have created a new conda environment via orbit and this issue still persists...any fixes ???

**Comment by 1412kauti** [comment]
```
(orbit2) kaito@comet:~/Documents/Expt/Orbit/Project_Code$ python
Python 3.7.16 (default, Jan 17 2023, 22:20:44) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torch.nn as nn
>>> from skrl.models.torch import Model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kaito/mambaforge-pypy3/envs/orbit2/lib/python3.7/site-packages/skrl/models/torch/__init__.py", line 1, in <module>
    from skrl.models.torch.base import Model
  File "/home/kaito/mambaforge-pypy3/envs/orbit2/lib/python3.7/site-packages/skrl/models/torch/base.py", line 4, in <module>
    import gymnasium
  File "/home/kaito/mambaforge-pypy3/envs/orbit2/lib/python3.7/site-packages/gymnasium/__init__.py", line 12, in <module>
    from gymnasium.envs.registration import (
  File "/home/kaito/mambaforge-pypy3/envs/orbit2/lib/python3.7/site-packages/gymnasium/envs/__init__.py", line 382, in <module>
    load_plugin_envs()
  File "/home/kaito/mambaforge-pypy3/envs/orbit2/lib/python3.7/site-packages/gymnasium/envs/registration.py", line 565, in load_plugin_envs
    for plugin in metadata.entry_points(group=entry_point):
TypeError: entry_points() got an unexpected keyword argument 'group'

```
I'm getting this issue while importing SKRL

**Comment by Toni-SM** [comment]
Hi @1412kauti 

It seems to be a `gymnasium` error. 

Which version do you have installed?
Run the following command to get it 

```bash
orbit -p -m pip show gymnasium
```

I have `gymnasium v0.27.1` and the import works.
You can install this version via:


```bash
orbit -p -m pip install gymnasium==0.27.1
```

**Comment by 1412kauti** [comment]
Turns out that I had to update gym, gymnasium and importlib_metadata

```
pip install --upgrade importlib_metadata
pip install --upgrade gymnasium
pip install --upgrade gym
```
cuz I tried to replicate the issue in another machine and I stumbled on the same errors in a different order

Got it fixed .... Thanx
